name: 'Snapcraft Publish'
description: 'Publish a Snapcraft project to the Snap Store'
author: 'James Henstridge'
branding:
  icon: 'upload'
  color: 'orange'
inputs:
  store_login:
    description: 'The login data for the Snap Store produced with "snapcraft export-login"'
    required: false
  snap:
    description: 'The snap file to upload to the store'
    required: true
  release:
    description: 'A comma separated list of channels to release the snap to'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
